const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const UPDATE_QTY_CART = "UPDATE_QTY_CART";
const SHOW_TOAST = "SHOW_TOAST";
const REMOVE_TOAST = "REMOVE_TOAST";
const GET_USER_INFO = "GET_USER_INFO";
const GET_CART = "GET_CART";
const SET_LOADING = "SET_LOADING";
const GET_CATEGORY = "GET_CATEGORY";
const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";
const SHOW_MODAL = "SHOW_MODAL";

export {
    ADD_TO_CART,
    REMOVE_FROM_CART,
    UPDATE_QTY_CART,
    SHOW_TOAST,
    REMOVE_TOAST,
    GET_USER_INFO,
    GET_CART,
    SET_LOADING,
    GET_CATEGORY,
    GET_SUB_CATEGORY,
    SHOW_MODAL
}